server:
  port: 8082

spring:
  application:
    name: INVENTORY-SERVICE
  profiles:
    active: dev

---

spring:
  profiles: test
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/sem-inventory-service-test
    username: sa
    password:

---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sem-inventory-service-dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---